# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 20

#[[main]]
#  name = "Projects"
 # url = "#projects"
#  weight = 30

#[[main]]
#  name = "Talks"
#  url = "#talks"
#  weight = 40

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

#[[main]] 
#  name = "Certifications"
#  url = "#certifications"    
#  weight = 40 

[[main]]
  name = "Awards"
  url = "#awards"
  weight = 40

#[[main]]
#  name = "Organizations"
#  url = "#organizations"
#  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
[[main]]
    name = "Resume"
    url = "media/resume.pdf"
    weight = 80
